name: 'publish'

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Gitbook
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish
        uses: dzoladz/GitLearning@main
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
